version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "main"
  reviewers:
    - "alorcoda"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "America/Edmonton"